## Arrays

In [2]:
import numpy as np
n=tuple(map(int,input().split()))
arr=np.array([input().split() for _ in range(n[-1])],int)
print(arr)

2 2
1 1
2 3
[[1 1]
 [2 3]]


## Shape and Reshape

In [1]:
import numpy as np
s=input()
a=list(map(int,s.split()))
print(np.reshape(np.array(a),(3,3)))



1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [2]:
import numpy as np
a=input().split()
v=[]
for _ in range(int(a[0])):
    r=input()
    s=list(map(int,r.split()))
    v.append(s)
my_array=np.array(v)
print(np.transpose(my_array))
print(my_array.flatten())



1 4
1 2 3 4
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


## Concatenate

In [3]:
import numpy as np
a=list(map(int,input().split()))
lista=np.array([input().split() for _ in range(a[0])],int)
listb=np.array([input().split() for _ in range(a[1])],int)
print(np.concatenate((lista,listb),axis=0))





1 1
1 2 3 4
5 6 7 8
[[1 2 3 4]
 [5 6 7 8]]


## Zeros and ones

In [4]:
import numpy as np
a=tuple(map(int,input().split()))
print(np.zeros((a),dtype=np.int))
print(np.ones((a),dtype=np.int))




3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


<ipython-input-4-55bf724b2b03>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.zeros((a),dtype=np.int))
<ipython-input-4-55bf724b2b03>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more

## Eye and Identity

In [5]:
import numpy as np
a=list(map(int,input().split()))
print(str(np.eye(a[0],a[1])).replace('1.',' 1.').replace('0.',' 0.'))




3 3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics

In [6]:
import numpy as np
x=tuple(map(int,input().split()))
i=[]
j=[]
for _ in range(x[0]):
    v=list(map(int,input().split()))
    i.append(v)
for _ in range(x[0]):
    w=list(map(int,input().split()))
    j.append(w)
   
   
a=np.array(i).reshape(x)
b=np.array(j).reshape(x)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep='\n')


1 4
1 2 3 4
2 3 4 5
[[3 5 7 9]]
[[-1 -1 -1 -1]]
[[ 2  6 12 20]]
[[0 0 0 0]]
[[1 2 3 4]]
[[   1    8   81 1024]]


## Floor Ceil and rint

In [8]:
import numpy as np
np.set_printoptions(legacy='1.13')
a=list(map(float,input().split()))
print(np.floor(a),np.ceil(a),np.rint(a),sep='\n')




1.3 1 4.5
[ 1.  1.  4.]
[ 2.  1.  5.]
[ 1.  1.  4.]


## Sum and Prod

In [9]:
import numpy as np
a=tuple(map(int,input().split()))
i=[]
for _ in range(a[0]):
    x=list(map(int,input().split()))
    i.append(x)
arr=np.array(i).reshape(a)
print(np.prod(np.sum(arr,axis=0)))





1 4
1 2 3 4
24


## Min and Max

In [10]:
import numpy as np
n=tuple(map(int,input().split()))
arr=np.array([input().split() for _ in range(n[-1])],int)
print(np.max(np.min(arr,axis=1)))





1 4
1 2 3 4
3 4 5 6
4 5 6 7
2 3 4 45
4


## Mean Var and Std

In [11]:
import numpy as np
n=tuple(map(int,input().split()))
arr=np.array([input().split() for _ in range(n[-1])],dtype=int)
print(np.mean(arr,axis=1),np.var(arr,axis=0),np.around(np.std(arr),11),sep='\n')





1 1
1 2 3 4
[ 2.5]
[ 0.  0.  0.  0.]
1.11803398875


## Dot and Cross

In [13]:
import numpy as np
n=int(input())
arr1=np.array([input().split() for _ in range(n)],int)
arr2=np.array([input().split() for _ in range(n)],int)
print(np.dot(arr1,arr2))




2
1 2
3 4
5 6
7 8
[[19 22]
 [43 50]]


## Inner and Outer

In [14]:
import numpy as np
a=np.array(list(map(int,input().split())))
b=np.array(list(map(int,input().split())))
print(np.inner(a,b))
print(np.outer(a,b))





1 2 3 4
5 6 7 8
70
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


## Polynomials

In [15]:
import numpy
print(numpy.polyval(list(map(float,input().split())),int(input())))



1 2 3 4
2
26.0


## Linear Algebra

In [17]:
import numpy as np
print(round(np.linalg.det(np.array([input().split() for _ in range(int(input()))],dtype=float)),2))


2
1 2
3 4
-2.0
